const fs = require('fs');
const path = require('path');

const TRUST_NAME = process.env.TRUST_NAME || 'Sri Sai Dharma Samrakshana Prema Kuteeram';
const TRUST_TAGLINE = process.env.TRUST_TAGLINE || 'Public Charitable Trust';

// Resolve the report logo: prefer the high-quality project-root logo, fall back
// to the smaller footer asset shipped under backend/assets.
const ROOT_LOGO = path.join(__dirname, '../../../logo.jpg');
const ASSET_LOGO = path.join(__dirname, '../../assets/logo-footer.jpg');
const LOGO_PATH =
  fs.existsSync(ROOT_LOGO) && fs.statSync(ROOT_LOGO).size > 0
    ? ROOT_LOGO
    : fs.existsSync(ASSET_LOGO)
    ? ASSET_LOGO
    : null;

// Reuse the email logo source (inline CID when available) so HTML reports show
// the same trust logo that the branded footer uses.
let TRUST_LOGO_SRC = process.env.TRUST_LOGO_URL || 'https://crmsaidharmasamrakshanapremakuteeram.dpdns.org/logo-footer.jpg';
try {
  const notify = require('@/services/notify');
  if (notify.LOGO_SRC) TRUST_LOGO_SRC = notify.LOGO_SRC;
} catch (e) {
  /* notify optional */
}

// Standard purpose statements — shown on every generated report so the reader
// always knows why the report exists.
const PURPOSES = {
  transactions:
    'This report is a complete record of all financial transactions maintained by the trust — every donation received ' +
    '(credit) and every expense incurred (debit), across cash and digital modes. It is generated for accounting, ' +
    'auditing and transparent review of the trust’s funds.',
  monthly:
    'This report is a periodic (monthly) summary of the trust’s financial activity. It presents the income (donations) ' +
    'and expenses for the month so that the trust’s management and stakeholders can monitor its financial position ' +
    'and ensure accountability.',
  scheduled:
    'This report is generated automatically as per the scheduled report "%NAME%" to provide a summary of transactions ' +
    'for the selected period (%START% to %END%), for record-keeping and review.',
};

function purposeFor(key, vars = {}) {
  let text = PURPOSES[key] || PURPOSES.transactions;
  for (const [k, v] of Object.entries(vars)) {
    text = text.replace(new RegExp('%' + k.toUpperCase() + '%', 'g'), v == null ? '' : String(v));
  }
  return text;
}

// Draw a branded header (logo + trust name + title + purpose + meta) on a
// PDFDocument. Returns the Y coordinate where report content should begin.
function drawPdfHeader(doc, opts = {}) {
  const { subtitle = '', purposeKey = 'transactions', purposeVars = {}, generatedBy = '', date = '' } = opts;
  const marginX = 40;
  const rightX = 815;

  if (LOGO_PATH) {
    try {
      doc.image(LOGO_PATH, rightX - 72, 32, { width: 64 });
    } catch (e) {
      /* logo is optional */
    }
  }

  doc.font('Helvetica-Bold').fontSize(16).fillColor('#1f2937')
    .text(TRUST_NAME, marginX, 36, { width: rightX - marginX - 90 });
  doc.font('Helvetica').fontSize(9).fillColor('#6b7280')
    .text(TRUST_TAGLINE, marginX, 58, { width: rightX - marginX - 90 });

  let y = 76;
  if (subtitle) {
    doc.font('Helvetica-Bold').fontSize(13).fillColor('#4338ca')
      .text(subtitle, marginX, y, { width: rightX - marginX - 90 });
    y += 18;
  }

  const purpose = purposeFor(purposeKey, purposeVars);
  doc.font('Helvetica').fontSize(8.5).fillColor('#6b7280')
    .text('Purpose: ' + purpose, marginX, y, { width: rightX - marginX - 90, lineGap: 2 });
  const purposeLines = doc.heightOfString('Purpose: ' + purpose, { width: rightX - marginX - 90, fontSize: 8.5, lineGap: 2 });
  y += purposeLines + 6;

  if (generatedBy || date) {
    doc.font('Helvetica').fontSize(8.5).fillColor('#9ca3af')
      .text(`Generated by: ${generatedBy || 'System'}  |  ${date || ''}`, marginX, y, { width: rightX - marginX - 90 });
    y += 14;
  }

  const dividerY = y + 2;
  doc.moveTo(marginX, dividerY).lineTo(rightX, dividerY).strokeColor('#e5e7eb').stroke();
  return dividerY + 12;
}

// HTML header block (logo + trust name + title + purpose) for email reports.
function reportHeaderHtml(opts = {}) {
  const { title = '', subtitle = '', purposeKey = 'transactions', purposeVars = {} } = opts;
  const purpose = purposeFor(purposeKey, purposeVars);
  return `
    <div style="text-align:left;margin-bottom:18px;">
      <img src="${TRUST_LOGO_SRC}" alt="${TRUST_NAME}" width="110" style="margin-bottom:8px;">
      <h2 style="margin:0 0 4px;color:#0b3c6d;font-size:20px;font-family:Arial,Helvetica,sans-serif;">${TRUST_NAME}</h2>
      <div style="color:#666;font-size:13px;margin-bottom:8px;font-family:Arial,Helvetica,sans-serif;">${TRUST_TAGLINE}</div>
      ${title ? `<h3 style="margin:0 0 6px;color:#4338ca;font-size:16px;font-family:Arial,Helvetica,sans-serif;">${title}</h3>` : ''}
      ${subtitle ? `<div style="color:#444;font-size:13px;margin-bottom:6px;font-family:Arial,Helvetica,sans-serif;">${subtitle}</div>` : ''}
      <p style="margin:0;color:#6b7280;font-size:12px;line-height:1.5;font-family:Arial,Helvetica,sans-serif;"><strong>Purpose:</strong> ${purpose}</p>
    </div>`;
}

// Write the branded header into an Excel worksheet. Returns the row number on
// which the data (column) header should be placed.
function addExcelHeader(sheet, opts = {}) {
  const { subtitle = '', purposeKey = 'transactions', purposeVars = {}, generatedBy = '', date = '', lastCol = 'J' } = opts;

  if (LOGO_PATH) {
    try {
      const imageId = sheet.workbook.addImage({ filename: LOGO_PATH, extension: 'jpeg' });
      // Anchor in column A (rows 1-4) so it does not overlap the title text in column B onward.
      sheet.addImage(imageId, 'A1:A4');
    } catch (e) {
      /* logo optional */
    }
  }

  sheet.mergeCells('B1:' + lastCol + '1');
  sheet.getCell('B1').value = TRUST_NAME;
  sheet.getCell('B1').font = { bold: true, size: 14, color: { argb: 'FF0B3C6D' } };

  sheet.mergeCells('B2:' + lastCol + '2');
  sheet.getCell('B2').value = TRUST_TAGLINE;
  sheet.getCell('B2').font = { italic: true, size: 10, color: { argb: 'FF6B7280' } };

  let row = 3;
  if (subtitle) {
    sheet.mergeCells('B3:' + lastCol + '3');
    sheet.getCell('B3').value = subtitle;
    sheet.getCell('B3').font = { bold: true, size: 12, color: { argb: 'FF4338CA' } };
    row = 4;
  }

  sheet.mergeCells('B' + row + ':' + lastCol + row);
  sheet.getCell('B' + row).value = 'Purpose: ' + purposeFor(purposeKey, purposeVars);
  sheet.getCell('B' + row).font = { size: 9, color: { argb: 'FF6B7280' } };
  sheet.getCell('B' + row).alignment = { wrapText: true, vertical: 'top' };
  sheet.getRow(row).height = 44;

  const metaRow = row + 1;
  if (generatedBy || date) {
    sheet.mergeCells('B' + metaRow + ':' + lastCol + metaRow);
    sheet.getCell('B' + metaRow).value = `Generated by: ${generatedBy || 'System'}  |  ${date || ''}`;
    sheet.getCell('B' + metaRow).font = { size: 9, color: { argb: 'FF9CA3AF' } };
  }

  return metaRow + 2;
}

module.exports = {
  TRUST_NAME,
  TRUST_TAGLINE,
  LOGO_PATH,
  TRUST_LOGO_SRC,
  PURPOSES,
  purposeFor,
  drawPdfHeader,
  reportHeaderHtml,
  addExcelHeader,
};
